apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-api
  namespace: mysql-cluster
  labels:
    app: ingest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingest-api
  template:
    metadata:
      labels:
        app: ingest-api
    spec:
      # --- INÍCIO DA SEÇÃO DO INIT CONTAINER ---
      # Este contêiner roda uma vez, antes do contêiner principal,
      # para garantir que o banco e a tabela existam.
      initContainers:
      - name: db-initializer
        # Usamos a MESMA imagem que o contêiner principal.
        # Lembre-se de construir sua imagem com uma tag de versão, ex: ingest-api:v1.1
        image: ingest-api:v1.1
        imagePullPolicy: IfNotPresent
        # O comando aqui é para executar APENAS o script de inicialização.
        command: ["python", "init_db.py"]
        # Ele precisa das mesmas variáveis de ambiente para se conectar ao banco.
        envFrom:
        - configMapRef:
            name: ingest-api-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypwds
              key: rootPassword
      # --- FIM DA SEÇÃO DO INIT CONTAINER ---

      # A definição do nosso contêiner principal da aplicação.
      containers:
      - name: api
        # Lembre-se de usar a mesma tag da imagem.
        image: ingest-api:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        # Carrega as variáveis de ambiente do ConfigMap e do Secret.
        envFrom:
        - configMapRef:
            name: ingest-api-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypwds
              key: rootPassword
