apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: mysql-cluster
spec:
  type: ClusterIP
  selector: 
    app: ingest-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
